"""Add language to Post table

Revision ID: 70671c10aed5
Revises: f3066dd31055
Create Date: 2020-03-16 12:47:56.551390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70671c10aed5'
down_revision = 'f3066dd31055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
